var map = [
    "1111111111111111111111111111111111111111111111111111111111111111111111111111111111  ",
    "                                                                                    ",
    "                                                                                    ",
    "            aaa1111111122222333344444                                               ",
    "33333333333333333                                                                   ",
    "                                                                                    ",
    "                                                                                    ",
    "                                                                                    ",
    "                                                                                    ",
    "                                                                                    ",
    "211111113111114                                                                     ",
    "                                                                                    ",
    "                                                                                    ",
    "                                                                                    ",
    " XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        44444      3333     2222    1111    ",
    "                                                                                    ",
    "                                                                                    ",
    "                                                                                    ",
    "                                                                                    ",
    "                                                                                    ",
    "   33aa33                                                                           ",
    " 33333333333444444444444444444444444444                                             ",
    "                                                                                    ",
    "                                                                                    ",
    "                                                                                    ",
    "                                                                                    ",
    "                                                                                    ",
    "                     aaaaaaaaaa                                                     ",
    " XXXXXXXXXXXXX333333333333333333                                                   X",
    "                                                                                    ",
    "                                                                                    ",
    " 1111111111111111111   aaaaaaaaa                                                    ",
    "                                                                                    ",
    "                                                                                    ",
    "213213213213                                                                        ",
    "                                                                                    ",
    "                                                                                    ",
    "                               aaaa                                                 ",
    " XXXXXXXXXXXXX 33333333333333333333333                                              ",
    "                                                                                    ",
    "                                                                                    ",
    "                                                                                    ",
    "             aaa                                                                    ",
    " XXXXXXXXXXXXXXXXXXXXX                                                              ",
    "                                                                                    ",
    "                                                                                    ",
    "                                                                                    ",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                    ",
    "                                                                                    ",
    "                                                                                    ",
    " 222222211111133333444444aaaaaaaaaaaaaaaaa                                          ",
    "                                                                                    ",
    "    aaa                                                                             ",
    "33333333333                                                                         ",
    "                                                                                    ",
    "                                                                                    ",
    "                                                                                    ",
    "                                                                                    ",
    "  33333333333333333333333333333333333333333333333333333333333333333333333333333333  "
];

var conf = {
    g: 0.05,
    maxVY: 0.5,
    jumpVy: 0.5,
    mainCharacter: new Character("main", 3, 8, 2, 3, 69, 194),
    blocks: {
        "a": "COIN",
        "2": "KILLING",
        "3": "KILLING"
    }
};

GameStarter.setWorld(new World(new WorldMap(map), conf));